name: superdiva_radio
description: Radio App Theme.
publish_to: 'none'
version: 2.1.0+6

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  radio_player: ^1.2.1
  share_plus: ^6.0.1
  flutter_markdown: ^0.6.13
  google_mobile_ads: ^2.3.0
  back_button_behavior: ^0.0.1
  provider: ^6.0.5
  sleek_circular_slider: ^2.0.1
  volume_regulator: ^2.1.0
  http: ^0.13.5
  dart_common_utils: ^1.0.0

  # Firebase dependencies
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.3.0

  # WordPress API integration
  wordpress_api: ^1.2.0+1
  

  # YouTube Live integration
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.9
  flutter_lints: ^2.0.0
  

flutter_native_splash:
  color: "#5477EF"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    color: "#5477EF"
    color_dark: "#5477EF"
    image: assets/splash/splash12.png
    image_dark: assets/splash/splash12.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/text/

flutter_icons: # flutter pub run flutter_launcher_icons:main
  image_path: "assets/images/appIcon.png"
  android: true
  ios: true